In [1]:
import numpy as np 
import pandas as pd

In [6]:
df = pd.read_csv('holidays_2024.csv')
df

,time,Is_Legal_Holiday,Is_School_Recess,Is_Event_Festival,Is_Early_Dismissal
0,2024-01-01 04:00:00,1,0,0,0
1,2024-01-01 04:30:00,1,0,0,0
2,2024-01-01 05:00:00,1,0,0,0
3,2024-01-01 05:30:00,1,0,0,0
4,2024-01-01 06:00:00,1,0,0,0
...,...,...,...,...,...
17554,2024-12-31 21:00:00,0,1,1,0
17555,2024-12-31 21:30:00,0,1,1,0
17556,2024-12-31 22:00:00,0,1,1,0
17557,2024-12-31 22:30:00,0,1,1,0
17558,2024-12-31 23:00:00,0,1,1,0

In [5]:
wdf = pd.read_csv('weather_2024.csv')
wdf

,time,temperature_2m,cloudcover,windspeed_10m,Rain_None,Rain_Light,Rain_Moderate,Rain_Heavy
0,2024-01-01 04:00:00,0.326491,1.000,0.109732,1,0,0,0
1,2024-01-01 04:30:00,0.326002,1.000,0.132139,1,0,0,0
2,2024-01-01 05:00:00,0.325513,1.000,0.154547,1,0,0,0
3,2024-01-01 05:30:00,0.335288,1.000,0.176620,1,0,0,0
4,2024-01-01 06:00:00,0.345064,1.000,0.198693,1,0,0,0
...,...,...,...,...,...,...,...,...
17554,2024-12-31 21:00:00,0.455523,0.870,0.177049,1,0,0,0
17555,2024-12-31 21:30:00,0.450635,0.930,0.169050,1,0,0,0
17556,2024-12-31 22:00:00,0.445748,0.990,0.161052,1,0,0,0
17557,2024-12-31 22:30:00,0.444770,0.995,0.175829,1,0,0,0
17558,2024-12-31 23:00:00,0.443793,1.000,0.190605,1,0,0,0

In [11]:
wdf[wdf["Rain_Heavy"] == 0].count()

time              17523
temperature_2m    17523
cloudcover        17523
windspeed_10m     17523
Rain_None         17523
Rain_Light        17523
Rain_Moderate     17523
Rain_Heavy        17523
dtype: int64